services:
  fastapi:
    build:
      context: ./fastapi_app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env.dev  # Adjust to .env.prod for production
    volumes:
      - ./config.py:/app/config.py  # Mount config.py from root directory

  celery:
    build:
      context: ./celery_worker
      dockerfile: Dockerfile
    env_file:
      - .env.dev  # Adjust to .env.prod for production
    volumes:
      - ./config.py:/app/config.py  # Mount config.py from root directory

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"


  mlflow:
    image: mlflow:latest
    ports:
      - "5000:5000"
    command: ["mlflow", "server", "--backend-store-uri", "sqlite:///mlflow.db", "--default-artifact-root", "./mlruns"]
    volumes:
      - ./mlflow.db:/mlflow.db
      - ./mlruns:/mlruns